# limits
FEATURED_PRODUCTS_LIMIT = 6
LOW_STOCK_THRESHOLD = 3
RECENT_PRODUCTS_LIMIT = 5
RELATED_PRODUCTS_LIMIT = 4

# categories
CATEGORY_ANIME = 'anime'
CATEGORY_STATIONERY = 'stationery'

# routes
ROUTE_ADMIN_DASHBOARD = 'admin.dashboard'