"""Add highlights column to Product

Revision ID: df3204e44ec5
Revises: eaad020612cf
Create Date: 2025-12-13 03:56:10.372296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3204e44ec5'
down_revision = 'eaad020612cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlights', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('highlights')

    # ### end Alembic commands ###
