"""Add discount fields to Product

Revision ID: eaad020612cf
Revises: 0b46114fef21
Create Date: 2025-12-05 02:37:03.699326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaad020612cf'
down_revision = '0b46114fef21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
